'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.'''

from functools import reduce

def getFib():
  list = [1]
  i = 1
  while list[i - 1] < 4000000:
    if i == 1:
      list.append(2)
    else:
      elem = list[i - 1] + list[i - 2] 
      list.append(elem)
    i = i + 1

  return list

seqFibEvenNumbs = list(filter(lambda x: x%2 == 0, getFib()))

sum = reduce(lambda x,y: x + y, seqFibEvenNumbs)

print(sum) # sum = 4613732

input()